spring:
  application.name: claims-service
  datasource:
    url: jdbc:postgresql://localhost:5432/claims
    username: claims
    password: claims
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
    properties.hibernate.jdbc.time_zone: UTC
  flyway.enabled: true
server.port: 8080
